### ISSUE TITLE
Error Installing 'functool' library

### ISSUE THREAD

**Issue by revantharunachalam** [CodeEZ-IoT/Python#2]
Sir, I tried to install the 'functools' library but I was interrupted by an error. I don't know how to solve this issue.
![functool](https://user-images.githubusercontent.com/44333953/63783417-9a792f80-c90a-11e9-8da1-80ccf824392f.JPG)

**Comment by CodeEZ-Dev** [comment]
Try to restart your computer and check. it will work.
